Keep carousel and dropdown in sync
hypergeek-dev/Santas-Devs pull request #29
Opened 2023-12-16 22:05 UTC by charleymroberts

Add event handlers to sync the carousel image canvas image and dropdown select

2023-12-16 22:55 UTC, BegumDev requested changes
The sync looks fine Charley however it's popped up that your branch is 'out of date with the main branch.' I'm guessing - have you pulled an up to date version before committing?

2023-12-16 23:56 UTC, charleymroberts commented
The only change on main was the merge of my previous PR - have rebased

2023-12-16 23:59 UTC, hypergeek-dev approved these changes

2023-12-17 09:27 UTC, hypergeek-dev approved these changes

2023-12-17 09:27 UTC, merged